//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC_NS_Evidencija.Backend.DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COACH
    {
        public COACH()
        {
            this.TRAININGs = new HashSet<TRAINING>();
        }
    
        public int PERSON_ID { get; set; }
        public string COACH_INTERNAL_ID { get; set; }
        public decimal PAYOFFRATE { get; set; }
        public decimal PAYMENTRATE { get; set; }
        public Nullable<decimal> PAYOFF { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<TRAINING> TRAININGs { get; set; }
    }
}
