//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC_NS_Evidencija.Backend.DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.MONTLYPAYMENTS = new HashSet<MONTLYPAYMENT>();
            this.STUDENT_TRAINING = new HashSet<STUDENT_TRAINING>();
        }
    
        public int PERSON_ID { get; set; }
        public string STUDENT_INTERNAL_ID { get; set; }
        public string PAYMENTTYPE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public string IMAGE_URL { get; set; }
        public string PARENT_FIRST_NAME { get; set; }
        public string PARENT_LAST_NAME { get; set; }
        public string PARENTS_MAIL { get; set; }
        public string PARENTS_TELEPHONE { get; set; }
        public Nullable<System.DateTime> BORN_DATE { get; set; }
        public string ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public string JMBG { get; set; }
        public Nullable<decimal> ToPay { get; set; }
    
        public virtual ICollection<MONTLYPAYMENT> MONTLYPAYMENTS { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<STUDENT_TRAINING> STUDENT_TRAINING { get; set; }
    }
}
