//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC_NS_Evidencija.Backend.DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TRAINING
    {
        public int PERSON_ID { get; set; }
        public int TRAINING_ID { get; set; }
        public string PAYMENTTYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string TRAININGQUALITY { get; set; }
        public string RELATIONSHIP { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual TRAINING TRAINING { get; set; }
    }
}
