//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC_NS_Evidencija.Backend.DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING
    {
        public TRAINING()
        {
            this.STUDENT_TRAINING = new HashSet<STUDENT_TRAINING>();
        }
    
        public int TRAINING_ID { get; set; }
        public Nullable<int> PERSON_ID { get; set; }
        public string TRAINING_INTERNAL_ID { get; set; }
        public int TRAININGTYPE { get; set; }
        public string TRAININGTHEME { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<double> DURATION { get; set; }
        public string NOTES { get; set; }
        public string TRAINING_QUALITY { get; set; }
        public string RELATIONSHIP { get; set; }
    
        public virtual COACH COACH { get; set; }
        public virtual ICollection<STUDENT_TRAINING> STUDENT_TRAINING { get; set; }
    }
}
